---
title: "Corpus pénurie d'eau"
format: html
editor: visual
---

### Set-up

```{r}
library(tidyverse)
library(strex)
library(rnaturalearth)
library(sf)
```

### Get corpus

```{r}
corpus = read.csv("collected_data/corpus_distinct.csv")

penurie = corpus %>% 
  filter(str_detect(text_en, "water scarcity|water shortage|shortage of water|water stress|lack of water")) %>% 
  select(c("fid", "position", "title", "link", "domain", "displayed_link", "snippet", "trans_snippet", "text", "text_en", "tokenized_text", "tokenized_noloc", "hl"))

write.csv(penurie, "analysis/penurie/corpus_penurie.csv")
```

#### Get number of pages per city

```{r}
citycodes = read.csv("input_data/citycodes.csv", sep = ";") %>% 
  select(c("ID", "fid"))

data_fusion = read.csv("input_data/data_city_river_fid_fusion.csv") %>% 
  select(c("fid", "fid_fusion", "urban_aggl", "latitude", "longitude")) %>% 
  left_join(citycodes, by = join_by("fid_fusion" == "fid"))

data_303 = read.csv("input_data/data_city_river_303.csv") %>% 
  select(c("fid", "urban_aggl"))

nb_penurie = penurie %>% 
  left_join(data_fusion, by = "fid") %>% 
  group_by(ID) %>% 
  count()

nb_penurie = rename(nb_penurie, nb = n)

write.csv(nb_penurie, "analysis/penurie/nb_occ_penurie_villes.csv")
write.csv(nb_penurie, "analysis/article_WS/data_LB.csv")
```

### Geophysical data

```{r}

### Préparation des données de Fanny 
data_fb = read.csv("analysis/penurie/data_FB.csv") 

data = data_fb %>% 
  mutate(study_zone = paste0(reach, "_", zone)) %>% 
  filter(!is.na(Urban_Aggl), !is.na(reach), !is.na(neg_perc)) %>% 
  select(c("Urban_Aggl", "study_zone", "neg_perc")) %>% 
  mutate(neg_perc = round(neg_perc, 3)) %>% 
  pivot_wider(names_from = study_zone, values_from = neg_perc) %>% 
  rowwise() %>%
  mutate(moy = mean(c_across(where(is.numeric)), na.rm = TRUE)) %>%
  mutate(max = max(c_across(where(is.numeric)), na.rm = TRUE)) %>% 
  ungroup()

write.csv(data, "analysis/penurie/data_FB_format.csv")

### V2
data_tt = data_fb %>% 
  group_by(citycode) %>% 
  summarize(tot_neg = sum(ntype_neg, na.rm = TRUE),
            tot_pos = sum(ntype_pos, na.rm = TRUE),
            tot_neu = sum(ntype_neut, na.rm = TRUE)) %>% 
  mutate(total = tot_neg + tot_pos + tot_neu) %>% 
  mutate(perc_neg = tot_neg/total*100,
         perc_pos = tot_pos/total*100,
         perc_neu = tot_neu/total*100) %>% 
  left_join(citycodes, by = join_by("citycode" == "ID"))

write.csv(data_tt, "analysis/article_WS/data_FB.csv")
```

### Map

```{r}
data_penurie = data_fusion %>% 
  mutate(latitude = as.numeric(str_replace_all(latitude, ",", "."))) %>% 
  mutate(longitude = as.numeric(str_replace_all(longitude, ",", "."))) %>% 
  left_join(nb_penurie, by = "ID") %>% 
  left_join(data_tt, by = join_by("ID" == "citycode")) %>% 
  mutate(nb = replace_na(nb, 0)) %>% 
  filter(!is.na(perc_neg)) %>% 
  select(-c(1,3)) %>% 
  unique() %>% 
  left_join(data_303, by = join_by("fid_fusion" == "fid"))
write.csv(data_penurie, "analysis/article_WS/data_penurie.csv")

# code by hand
data_penurie = read.csv("analysis/article_WS/data_penurie_code.csv")

data_sf = st_as_sf(data_penurie, coords = c("longitude", "latitude"), crs = 4326)

# map
world_map = ne_countries(scale = "medium", returnclass = "sf")

# map max
world_map %>% 
  ggplot() +
  # world map 
  geom_sf(fill = "#f0f0f1", color = "white", size = 0.2) +
  # city points
  geom_sf(data = data_sf, 
          aes(size = nb,
              color = perc_neg),
          alpha = 0.8) +
  scale_color_viridis_b() +
   # equal earth projection
  coord_sf(crs = "+proj=eqearth") +
  # theme
  theme_void() +
  theme(legend.position = "bottom",
        legend.box = "vertical",
        plot.background = element_rect(fill = "white")) +
  labs(size = "Nombre d'occurrences dans le corpus",
       col = "Pourcentage moyen de pixels négatifs") 
ggsave("analysis/article_WS/map_FB_LB.svg", width = 4000, height = 2500, units = "px")
ggsave("analysis/article_WS/map_FB_LB.png", width = 4000, height = 2500, units = "px")
```

### Cities to analyse

```{r}
penurie_analysis = data_penurie %>% 
  filter(nb > 3 | max >= 0.75) %>% 
  select(c("fid", "urban_aggl", "country_fr", "riviere", "nb", "city_plain", "downstream_plain", "upstream_plain", "city_corridor", "downstream_corridor", "upstream_corridor", "moy", "max"))

write.csv(penurie_analysis, "analysis/penurie/liste_villes_penurie.csv")
```

### Cube de corrélation

```{r}
data_cube = data_penurie %>% 
  mutate(classe = case_when(
    perc_neg > 32.2439 & data_corpus == 1 ~ "B",
    perc_neg > 32.2439 &  data_corpus == 0  ~ "A",
    perc_neg < 32.2439 &  data_corpus == 1 ~ "D",
    perc_neg < 32.2439 &  data_corpus == 0 ~ "C"))

nb_cube = data_cube %>% 
  group_by(classe) %>% 
  count()

data_sf = st_as_sf(data_cube, coords = c("longitude", "latitude"), crs = 4326)

world_map %>% 
  ggplot() +
  # world map 
  geom_sf(fill = "#f0f0f1", color = "white", size = 0.2) +
  # city points
  geom_sf(data = data_sf, 
          aes(color = classe),
          alpha = 0.8) +
  scale_color_manual(breaks = c("A", "B", "C", "D"),
                     values = c("#8dd3c7", "#fb8072",  "#b3de69", "#fdb462")) +
   # equal earth projection
  coord_sf(crs = "+proj=eqearth") +
  # theme
  theme_void() +
  theme(legend.position = "bottom",
        legend.box = "vertical",
        plot.background = element_rect(fill = "white")) 
ggsave("analysis/article_WS/typologie_ws.png", width = 4000, height = 2500, units = "px")
```

\
