---
title: "Corpus riverfront - axe 2"
format: html
editor: visual
---

### Set-up

```{r}
library(tidyverse)
library(strex)
library(rnaturalearth)
library(sf)
```

### Read data

```{r}
corpus = read.csv("collected_data/corpus_distinct.csv")
fid_fusion = read.csv("input_data/data_city_river_fid_fusion.csv") %>% 
  select(c("fid","fid_fusion"))
noms_villes = read.csv("input_data/data_city_river_303.csv") %>%
  select(c("fid", "urban_aggl", "country_en"))
```

### Get riverfront data

#### Get riverfront corpus

```{r}
riverfront = corpus %>% 
  filter(str_detect(text_en, "riverfront|waterfront"))

write.csv(riverfront, "analysis/riverfront/corpus_riverfront.csv")
```

#### Get number of pages per city

```{r}
nb_riverfront = riverfront %>% 
  left_join(fid_fusion, by = "fid") %>% 
  group_by(fid_fusion) %>% 
  count() %>% 
  rename("n_tot" = "n") %>% 
  left_join(noms_villes, by = join_by("fid_fusion" == "fid"))

write.csv(nb_riverfront, "analysis/riverfront/nb_occ_riverfront_villes.csv")
```

### Map

```{r}
data_penurie = read.csv("input_data/data_city_river.csv") %>% 
  mutate(latitude = as.numeric(str_replace_all(latitude, ",", "."))) %>% 
  mutate(longitude = as.numeric(str_replace_all(longitude, ",", "."))) %>% 
  left_join(nb_penurie, by = "urban_aggl") %>% 
  left_join(data, by = join_by("urban_aggl" == "Urban_Aggl")) 

data_sf = st_as_sf(data_penurie, coords = c("longitude", "latitude"),crs = 4326)

# map
world_map = ne_countries(scale = "medium", returnclass = "sf")

# map max
world_map %>% 
  ggplot() +
  # world map 
  geom_sf(fill = "#f0f0f1", color = "white", size = 0.2) +
  # city points
  geom_sf(data = data_sf, 
          aes(size = nb,
              color = cat_negatif),
          alpha = 0.8) +
  scale_color_manual(breaks = c("Plus de 80 %", "80 à 60 %", "60 à 40 %", "40 à 20 %", "Moins de 20 %", "Pas de données"),
                    values =c("#d7191c", "#fdae61", "#ffffbf", "#a6d96a", "#1a9641", "#bababa")) + 
   # equal earth projection
  coord_sf(crs = "+proj=eqearth") +
  # theme
  theme_void() +
  theme(legend.position = "bottom",
        legend.box = "vertical",
        plot.background = element_rect(fill = "white")) +
  labs(size = "Nombre d'occurrences dans le corpus",
       col = "Pourcentage maximal de pixels négatifs dans la ville") 
ggsave("analysis/penurie/map_penurie_max.svg", width = 4000, height = 2500, units = "px")
ggsave("analysis/penurie/map_penurie_max.png", width = 4000, height = 2500, units = "px")
```

### Cities to analyse

```{r}
penurie_analysis = data_penurie %>% 
  filter(nb > 3 | max >= 0.5) %>% 
  select(c("fid", "urban_aggl", "country_fr", "riviere", "nb", "city_plain", "downstream_plain", "upstream_plain", "city_corridor", "downstream_corridor", "upstream_corridor", "moy", "max"))

write.csv(penurie_analysis, "analysis/penurie/liste_villes_penurie.csv")
```
